---
- name: Install required packages
  ansible.builtin.package:
    name:
      - ipa-client
      - python3-pip
    state: installed
- name: Install pexpect
  ansible.builtin.pip:
    name: pexpect
    state: present
- name: Add host to IPA server
  ansible.builtin.expect:
    command: ipa-client-install --mkhomedir --no-ntp --no-nisdomain --hostname {{ inventory_hostname }} --principal {{ theforeman_custom_aide_for_audit_tools_ipaadmin_principal }} --password {{ theforeman_custom_aide_for_audit_tools_ipaadmin_password }}
    responses:
      'Continue to configure the system with these values': 'yes'
  register: result
  changed_when:
    - result.rc == 0
  failed_when:
    - result.rc != 0
    - result.rc != 3
